### ISSUE TITLE
Explicit valence for atom # 7 C, 5, is greater than permitted ERROR: Could not sanitize molecule ending on line 5729584

### ISSUE THREAD

**Issue by gittanzhao** [yongqyu/MolGAN-pytorch#3]
When I run sparse_molecular_dataset.py ,I get the error -- 'Explicit valence for atom # 7 C, 5, is greater than permitted ERROR: Could not sanitize molecule ending on line 5729584' and 'numpy.core._internal.AxisError: axis -1 is out of bounds for array of dimension 0'. 

Can you share your the file of 'gdb9_9nodes.sparsedataset'?  Thanks!

**Comment by yongqyu** [comment]
Sorry, but I do not have that file anymore.
The problem is not well understood.
If possible, please provide further explanation.

Thank you.

**Comment by gittanzhao** [comment]
Thanks for your reply!(I'm sorry that I don't have a good understanding of this field, so I may not have a good understanding of the content of the error report.I am mainly interested in your algorithm ideas and very inspired, thanks for your contribution!)
When I run the program, the error report of the terminal is as follows:


rosfun@ubuntu:~/anaconda2/envs/geek-ai/MolGAN$ python utils/sparse_molecular_dataset.py 


2019-07-15 14:39:47 Extracting data/gdb9.sdf..
[14:39:48] Explicit valence for atom # 1 C, 5, is greater than permitted
[14:39:48] ERROR: Could not sanitize molecule ending on line 9097
[14:39:48] ERROR: Explicit valence for atom # 1 C, 5, is greater than permitted
[14:39:48] Explicit valence for atom # 1 C, 5, is greater than permitted
[14:39:48] ERROR: Could not sanitize molecule ending on line 35785
[14:39:48] ERROR: Explicit valence for atom # 1 C, 5, is greater than permitted
[14:39:48] Explicit valence for atom # 4 C, 5, is greater than permitted
[14:39:48] ERROR: Could not sanitize molecule ending on line 62866
[14:39:48] ERROR: Explicit valence for atom # 4 C, 5, is greater than permitted
[14:39:48] Explicit valence for atom # 2 C, 5, is greater than permitted
[14:39:48] ERROR: Could not sanitize molecule ending on line 66832


...
...
...
[14:40:03] Explicit valence for atom # 7 C, 5, is greater than permitted
[14:40:03] ERROR: Could not sanitize molecule ending on line 5729263
[14:40:03] ERROR: Explicit valence for atom # 7 C, 5, is greater than permitted
[14:40:03] Explicit valence for atom # 6 C, 5, is greater than permitted
[14:40:03] ERROR: Could not sanitize molecule ending on line 5729540
[14:40:03] ERROR: Explicit valence for atom # 6 C, 5, is greater than permitted
[14:40:03] Explicit valence for atom # 7 C, 5, is greater than permitted
[14:40:03] ERROR: Could not sanitize molecule ending on line 5729584
[14:40:03] ERROR: Explicit valence for atom # 7 C, 5, is greater than permitted
2019-07-15 14:40:03 Extracted 133247 out of 133885 molecules not adding Hydrogen!
2019-07-15 14:40:03 Creating atoms encoder and decoder..
2019-07-15 14:40:06 Created atoms encoder and decoder with 4 atom types and 1 PAD symbol!
2019-07-15 14:40:06 Creating bonds encoder and decoder..
2019-07-15 14:40:09 Created bonds encoder and decoder with 4 bond types and 1 PAD symbol!
2019-07-15 14:40:09 Creating SMILES encoder and decoder..
2019-07-15 14:40:13 Created SMILES encoder and decoder with 26 types and 1 PAD symbol!
2019-07-15 14:40:13 Creating features and adjacency matrices..
()


None


Traceback (most recent call last):
  File "utils/sparse_molecular_dataset.py", line 331, in <module>
    data.generate('data/gdb9.sdf', filters=lambda x: x.GetNumAtoms() <= 9)
  File "utils/sparse_molecular_dataset.py", line 53, in generate
    self._generate_AX()
  File "utils/sparse_molecular_dataset.py", line 148, in _generate_AX
    D = np.count_nonzero(A, -1)
  File "/home/rosfun/anaconda2/envs/geek-ai/lib/python3.6/site-packages/numpy/core/numeric.py", line 444, in count_nonzero
    axis = asarray(normalize_axis_tuple(axis, a.ndim))
  File "/home/rosfun/anaconda2/envs/geek-ai/lib/python3.6/site-packages/numpy/core/numeric.py", line 1536, in normalize_axis_tuple
    axis = tuple(normalize_axis_index(ax, ndim, argname) for ax in axis)
  File "/home/rosfun/anaconda2/envs/geek-ai/lib/python3.6/site-packages/numpy/core/numeric.py", line 1536, in <genexpr>
    axis = tuple(normalize_axis_index(ax, ndim, argname) for ax in axis)
numpy.core._internal.AxisError: axis -1 is out of bounds for array of dimension 0









------------------ 原始邮件 ------------------
发件人: "yongqyu"<notifications@github.com>; 
发送时间: 2019年7月16日(星期二) 下午5:05
收件人: "yongqyu/MolGAN-pytorch"<MolGAN-pytorch@noreply.github.com>; 
抄送: "湖南大学谭朝"<993317238@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yongqyu/MolGAN-pytorch] Explicit valence for atom # 7 C, 5, isgreater than permitted ERROR: Could not sanitize molecule ending on line5729584 (#3)




Sorry, but I do not have that file anymore.
 The problem is not well understood.
 If possible, please provide further explanation.
 
Thank you.

**Comment by yongqyu** [comment]
First of all, this idea is not my idea.
If you refer to the README, you can also check the original paper and the tensorflow code.
My repository is simply a re-implementation of the code.

And above 

> "Explicit valence ..."

 can be ignored.
It is an issue that occurs because chemical conditions are not satisfied because it is still in the early stage of learning.

```
File "utils / sparse_molecular_dataset.py", line 148, in _generate_AX
     D = np.count_nonzero (A, -1)
```
I think you need to check ```A``` well in this part.

**Comment by gittanzhao** [comment]
I looked it up that A  always equal to None .Thanks for your reply. I will try again.
In addition, if you can generate a sparse_molecular_dataset file, could you send it to me via email? Thanks so much.I really need it!


Thank you !


------------------ 原始邮件 ------------------
发件人: "yongqyu"<notifications@github.com>;
发送时间: 2019年7月16日(星期二) 下午5:21
收件人: "yongqyu/MolGAN-pytorch"<MolGAN-pytorch@noreply.github.com>;
抄送: "湖南大学谭朝"<993317238@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yongqyu/MolGAN-pytorch] Explicit valence for atom # 7 C, 5, isgreater than permitted ERROR: Could not sanitize molecule ending on line5729584 (#3)




First of all, this idea is not my idea.
 If you refer to the README, you can also check the original paper and the tensorflow code.
 My repository is simply a re-implementation of the code.
 
And above
  
"Explicit valence ..."
  
can be ignored.
 It is an issue that occurs because chemical conditions are not satisfied because it is still in the early stage of learning.
 File "utils / sparse_molecular_dataset.py", line 148, in _generate_AX      D = np.count_nonzero (A, -1)  
I think you need to check A well in this part.

**Comment by yongqyu** [comment]
I do not have any data anymore.
I'm sorry about that part.

**Comment by gittanzhao** [comment]
ok！Thank you!


 
---Original---
